//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHKH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONGTRINHDUAN
    {
        public int ID { get; set; }
        public int ID_KYQH { get; set; }
        public string TENCONGTRINH { get; set; }
        public string MACT { get; set; }
        public Nullable<decimal> NAMTH { get; set; }
        public Nullable<decimal> DIENTICH_KH { get; set; }
        public Nullable<decimal> DIENTICH_HT { get; set; }
        public Nullable<decimal> DIENTICH_TANGTHEM { get; set; }
        public string SUDUNGVAOLD { get; set; }
        public string TENDIADIEM { get; set; }
        public string VITRITRENBD { get; set; }
        public string MAXA { get; set; }
        public string MAHUYEN { get; set; }
        public Nullable<int> ID_LOAICT { get; set; }
        public Nullable<bool> CAPTINH { get; set; }
        public System.Guid ROWID { get; set; }
    
        public virtual KYQUYHOACHKEHOACH KYQUYHOACHKEHOACH { get; set; }
        public virtual DM_LOAICONGTRINH DM_LOAICONGTRINH { get; set; }
        public virtual DM_KVHC DM_KVHC { get; set; }
        public virtual DM_KVHC DM_KVHC1 { get; set; }
    }
}
