//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHKH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_KVHC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DM_KVHC()
        {
            this.CONGTRINHDUANs = new HashSet<CONGTRINHDUAN>();
            this.CONGTRINHDUANs1 = new HashSet<CONGTRINHDUAN>();
            this.TH_CHUCHUYENDATDAI = new HashSet<TH_CHUCHUYENDATDAI>();
            this.HIENTRANGs = new HashSet<HIENTRANG>();
            this.KEHOACHes = new HashSet<KEHOACH>();
            this.KEHOACH_CMD = new HashSet<KEHOACH_CMD>();
            this.KEHOACH_CSD = new HashSet<KEHOACH_CSD>();
            this.KEHOACH_THUHOI = new HashSet<KEHOACH_THUHOI>();
            this.KHUCHUCNANGs = new HashSet<KHUCHUCNANG>();
            this.PHANBO_XACDINH = new HashSet<PHANBO_XACDINH>();
            this.QUYHOACHes = new HashSet<QUYHOACH>();
            this.MAP_CONFIG = new HashSet<MAP_CONFIG>();
            this.TH_CHUCHUYENDATDAI1 = new HashSet<TH_CHUCHUYENDATDAI>();
            this.HIENTRANGs1 = new HashSet<HIENTRANG>();
            this.KEHOACHes1 = new HashSet<KEHOACH>();
            this.KEHOACH_CMD1 = new HashSet<KEHOACH_CMD>();
            this.KEHOACH_CSD1 = new HashSet<KEHOACH_CSD>();
            this.KEHOACH_THUHOI1 = new HashSet<KEHOACH_THUHOI>();
            this.KHUCHUCNANGs1 = new HashSet<KHUCHUCNANG>();
            this.PHANBO_XACDINH1 = new HashSet<PHANBO_XACDINH>();
            this.QUYHOACHes1 = new HashSet<QUYHOACH>();
        }
    
        public string MA_KVHC { get; set; }
        public Nullable<int> ID_CAP_KVHC { get; set; }
        public string MA_KVHC_CHA { get; set; }
        public string TEN_KVHC { get; set; }
        public Nullable<decimal> STT_XA { get; set; }
        public string DIACHI { get; set; }
        public Nullable<decimal> DIENTICH { get; set; }
        public Nullable<decimal> DANGNONGNGHIEP { get; set; }
        public Nullable<decimal> DANGPHINONGNGHIEP { get; set; }
        public Nullable<bool> DELETED { get; set; }
        public Nullable<decimal> ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONGTRINHDUAN> CONGTRINHDUANs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONGTRINHDUAN> CONGTRINHDUANs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TH_CHUCHUYENDATDAI> TH_CHUCHUYENDATDAI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HIENTRANG> HIENTRANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KEHOACH> KEHOACHes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KEHOACH_CMD> KEHOACH_CMD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KEHOACH_CSD> KEHOACH_CSD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KEHOACH_THUHOI> KEHOACH_THUHOI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHUCHUCNANG> KHUCHUCNANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHANBO_XACDINH> PHANBO_XACDINH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUYHOACH> QUYHOACHes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAP_CONFIG> MAP_CONFIG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TH_CHUCHUYENDATDAI> TH_CHUCHUYENDATDAI1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HIENTRANG> HIENTRANGs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KEHOACH> KEHOACHes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KEHOACH_CMD> KEHOACH_CMD1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KEHOACH_CSD> KEHOACH_CSD1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KEHOACH_THUHOI> KEHOACH_THUHOI1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHUCHUCNANG> KHUCHUCNANGs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHANBO_XACDINH> PHANBO_XACDINH1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUYHOACH> QUYHOACHes1 { get; set; }
    }
}
