//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHKH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_LOAICONGTRINH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DM_LOAICONGTRINH()
        {
            this.CONGTRINHDUANs = new HashSet<CONGTRINHDUAN>();
        }
    
        public int ID { get; set; }
        public string LOAIHANGMUC { get; set; }
        public Nullable<bool> CAPTINH { get; set; }
        public string CHIMUC { get; set; }
        public Nullable<int> ID_CAPTREN { get; set; }
        public System.Guid ROWID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONGTRINHDUAN> CONGTRINHDUANs { get; set; }
    }
}
