//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHKH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_LOAIKHUCHUCNANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DM_LOAIKHUCHUCNANG()
        {
            this.KEHOACHes = new HashSet<KEHOACH>();
            this.PHANBO_XACDINH = new HashSet<PHANBO_XACDINH>();
            this.QUYHOACHes = new HashSet<QUYHOACH>();
            this.KHUCHUCNANGs = new HashSet<KHUCHUCNANG>();
        }
    
        public int ID { get; set; }
        public string KYHIEU { get; set; }
        public string TEN { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
        public Nullable<bool> ENABLED { get; set; }
        public Nullable<bool> CAPTINH { get; set; }
        public System.Guid ROWID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KEHOACH> KEHOACHes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHANBO_XACDINH> PHANBO_XACDINH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUYHOACH> QUYHOACHes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHUCHUCNANG> KHUCHUCNANGs { get; set; }
    }
}
