//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHKH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_MUCDICHSUDUNG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DM_MUCDICHSUDUNG()
        {
            this.HIENTRANGs = new HashSet<HIENTRANG>();
            this.KEHOACHes = new HashSet<KEHOACH>();
            this.KEHOACH_CSD = new HashSet<KEHOACH_CSD>();
            this.KEHOACH_THUHOI = new HashSet<KEHOACH_THUHOI>();
            this.KHUCHUCNANG_MDSD = new HashSet<KHUCHUCNANG_MDSD>();
            this.QUYHOACHes = new HashSet<QUYHOACH>();
            this.TH_CHUCHUYENDATDAI = new HashSet<TH_CHUCHUYENDATDAI>();
            this.TH_KYTRUOC = new HashSet<TH_KYTRUOC>();
            this.TH_CHUCHUYENDATDAI1 = new HashSet<TH_CHUCHUYENDATDAI>();
            this.PHANBO_XACDINH = new HashSet<PHANBO_XACDINH>();
        }
    
        public int ID { get; set; }
        public string KIHIEU { get; set; }
        public string TEN { get; set; }
        public Nullable<decimal> ID_CAPTREN { get; set; }
        public string CHIMUC { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
        public Nullable<bool> ENABLED { get; set; }
        public Nullable<bool> TT23 { get; set; }
        public Nullable<bool> TT24 { get; set; }
        public Nullable<bool> TT25 { get; set; }
        public Nullable<bool> TT01 { get; set; }
        public Nullable<bool> CAPTINH { get; set; }
        public Nullable<int> STT { get; set; }
        public System.Guid ROWID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HIENTRANG> HIENTRANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KEHOACH> KEHOACHes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KEHOACH_CSD> KEHOACH_CSD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KEHOACH_THUHOI> KEHOACH_THUHOI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHUCHUCNANG_MDSD> KHUCHUCNANG_MDSD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUYHOACH> QUYHOACHes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TH_CHUCHUYENDATDAI> TH_CHUCHUYENDATDAI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TH_KYTRUOC> TH_KYTRUOC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TH_CHUCHUYENDATDAI> TH_CHUCHUYENDATDAI1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHANBO_XACDINH> PHANBO_XACDINH { get; set; }
    }
}
