//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHKH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KEHOACH_CMD
    {
        public int ID { get; set; }
        public Nullable<int> ID_KYQH { get; set; }
        public Nullable<int> NAM { get; set; }
        public Nullable<int> ID_CMD { get; set; }
        public Nullable<decimal> DIENTICH { get; set; }
        public string MAXA { get; set; }
        public string MAHUYEN { get; set; }
        public Nullable<bool> CAPTINH { get; set; }
        public System.Guid ROWID { get; set; }
    
        public virtual DM_CHUYENMUCDICH DM_CHUYENMUCDICH { get; set; }
        public virtual DM_KVHC DM_KVHC { get; set; }
        public virtual DM_KVHC DM_KVHC1 { get; set; }
        public virtual KYQUYHOACHKEHOACH KYQUYHOACHKEHOACH { get; set; }
    }
}
