//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHKH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHUCHUCNANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHUCHUCNANG()
        {
            this.KHUCHUCNANG_MDSD = new HashSet<KHUCHUCNANG_MDSD>();
        }
    
        public int ID { get; set; }
        public int ID_KYQH { get; set; }
        public string MAKHUCN { get; set; }
        public string MAXA { get; set; }
        public string MAHUYEN { get; set; }
        public Nullable<int> MALOAIKHUCN { get; set; }
        public Nullable<bool> CAPTINH { get; set; }
        public string TENVUNG { get; set; }
        public System.Guid ROWID { get; set; }
    
        public virtual DM_KVHC DM_KVHC { get; set; }
        public virtual DM_KVHC DM_KVHC1 { get; set; }
        public virtual DM_LOAIKHUCHUCNANG DM_LOAIKHUCHUCNANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHUCHUCNANG_MDSD> KHUCHUCNANG_MDSD { get; set; }
        public virtual KYQUYHOACHKEHOACH KYQUYHOACHKEHOACH { get; set; }
    }
}
