//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHKH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHUCHUCNANG_MDSD
    {
        public int ID { get; set; }
        public int ID_KHUCN { get; set; }
        public int ID_MDSD { get; set; }
        public decimal DIENTICH { get; set; }
        public System.Guid ROWID { get; set; }
    
        public virtual DM_MUCDICHSUDUNG DM_MUCDICHSUDUNG { get; set; }
        public virtual KHUCHUCNANG KHUCHUCNANG { get; set; }
    }
}
