//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHKH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KYQUYHOACHKEHOACH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KYQUYHOACHKEHOACH()
        {
            this.CONGTRINHDUANs = new HashSet<CONGTRINHDUAN>();
            this.HIENTRANGs = new HashSet<HIENTRANG>();
            this.KEHOACHes = new HashSet<KEHOACH>();
            this.KEHOACH_CMD = new HashSet<KEHOACH_CMD>();
            this.KEHOACH_THUHOI = new HashSet<KEHOACH_THUHOI>();
            this.KHUCHUCNANGs = new HashSet<KHUCHUCNANG>();
            this.MAP_CONFIG = new HashSet<MAP_CONFIG>();
            this.PHANBO_XACDINH = new HashSet<PHANBO_XACDINH>();
            this.QUYHOACHes = new HashSet<QUYHOACH>();
            this.TH_CHUCHUYENDATDAI = new HashSet<TH_CHUCHUYENDATDAI>();
            this.TH_KYTRUOC = new HashSet<TH_KYTRUOC>();
            this.TH_KYTRUOC1 = new HashSet<TH_KYTRUOC>();
        }
    
        public int ID { get; set; }
        public string TEN { get; set; }
        public Nullable<int> NAM { get; set; }
        public Nullable<int> TUNAM { get; set; }
        public Nullable<int> TOINAM { get; set; }
        public Nullable<bool> BIKHOA { get; set; }
        public Nullable<int> IS_KEHOACH_DIEUCHINH { get; set; }
        public Nullable<int> ID_CHA { get; set; }
        public System.Guid ROWID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONGTRINHDUAN> CONGTRINHDUANs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HIENTRANG> HIENTRANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KEHOACH> KEHOACHes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KEHOACH_CMD> KEHOACH_CMD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KEHOACH_THUHOI> KEHOACH_THUHOI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHUCHUCNANG> KHUCHUCNANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAP_CONFIG> MAP_CONFIG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHANBO_XACDINH> PHANBO_XACDINH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUYHOACH> QUYHOACHes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TH_CHUCHUYENDATDAI> TH_CHUCHUYENDATDAI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TH_KYTRUOC> TH_KYTRUOC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TH_KYTRUOC> TH_KYTRUOC1 { get; set; }
    }
}
