//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHKH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_dbms_sql_define_column
    {
        public int cursor_id { get; set; }
        public int position { get; set; }
        public string C_type { get; set; }
    
        public virtual t_dbms_sql_cursor t_dbms_sql_cursor { get; set; }
    }
}
