//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHKH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_dbms_sql_cursor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_dbms_sql_cursor()
        {
            this.t_dbms_sql_bind_variable = new HashSet<t_dbms_sql_bind_variable>();
            this.t_dbms_sql_define_column = new HashSet<t_dbms_sql_define_column>();
            this.t_dbms_sql_recordset = new HashSet<t_dbms_sql_recordset>();
        }
    
        public int id { get; set; }
        public int spid { get; set; }
        public System.DateTime login_time { get; set; }
        public string statement { get; set; }
        public Nullable<int> current_row { get; set; }
        public Nullable<int> last_row { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_dbms_sql_bind_variable> t_dbms_sql_bind_variable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_dbms_sql_define_column> t_dbms_sql_define_column { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_dbms_sql_recordset> t_dbms_sql_recordset { get; set; }
    }
}
