//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHKH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH_KYTRUOC
    {
        public int ID { get; set; }
        public Nullable<int> ID_KYQH { get; set; }
        public Nullable<int> ID_KYQHTRUOC { get; set; }
        public Nullable<int> ID_MDSD { get; set; }
        public Nullable<decimal> DT_PHEDUYET { get; set; }
        public Nullable<decimal> DT_THUCHIEN { get; set; }
        public Nullable<decimal> TANG_GIAM { get; set; }
        public Nullable<decimal> TILE { get; set; }
        public string MAHUYEN { get; set; }
        public Nullable<bool> CAPTINH { get; set; }
        public System.Guid ROWID { get; set; }
    
        public virtual DM_MUCDICHSUDUNG DM_MUCDICHSUDUNG { get; set; }
        public virtual KYQUYHOACHKEHOACH KYQUYHOACHKEHOACH { get; set; }
        public virtual KYQUYHOACHKEHOACH KYQUYHOACHKEHOACH1 { get; set; }
    }
}
