//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHKH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERTABLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USERTABLE()
        {
            this.USERTABLE_LOG = new HashSet<USERTABLE_LOG>();
        }
    
        public int ID { get; set; }
        public string HOTEN { get; set; }
        public string TENDANGNHAP { get; set; }
        public string MATKHAU { get; set; }
        public string TENPHONGBAN { get; set; }
        public string MAPHONGBAN { get; set; }
        public Nullable<int> MAPHONGBANCHA { get; set; }
        public bool ENABLE { get; set; }
        public string GHICHU { get; set; }
        public System.Guid ROWID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USERTABLE_LOG> USERTABLE_LOG { get; set; }
    }
}
