//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHKH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERTABLE_LOG
    {
        public int ID { get; set; }
        public Nullable<int> ID_USER { get; set; }
        public Nullable<System.DateTime> THOIGIAN { get; set; }
        public string NOIDUNG { get; set; }
        public string KEY { get; set; }
        public System.Guid ROWID { get; set; }
    
        public virtual USERTABLE USERTABLE { get; set; }
    }
}
